/**
 * AI3 Open API Specification
 * AI3 Open API Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ai3@tdm.estgv.ipv.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SupportResponse { 
    message?: string;
}