/**
 * AI3 Open API Specification
 * AI3 Open API Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ai3@tdm.estgv.ipv.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserProfile { 
    sub: string;
    name?: string;
    givenName?: string;
    familyName?: string;
    middleName?: string;
    nickname?: string;
    preferredUsername?: string;
    profile?: string;
    picture?: string;
    website?: string;
    email: string;
    emailVerified?: boolean;
    gender?: string;
    birthdate?: string;
    zoneinfo?: string;
    locale?: string;
    phoneNumber?: string;
    phoneNumberVerified?: boolean;
    address?: any;
    /**
     * Timestamp of last update
     */
    updatedAt?: number;
} 